# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html for more info

[sncast.default]
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "trustpay_deployer"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "Voyager"
show-explorer-links = true
